language: node_js
dist: jammy
node_js:
  - '20'
services:
  - docker
env:
  global:
    - HL_BASE_IMAGE="1.0.0-20240126-1"
before_install:
  - pip install --user awscli
  - npm install -g yarn
install:
  - yarn install
  
script:
  - yarn lint

after_success:
  - if [ "x$TRAVIS_TAG" != "x" ]; then
    VER=$TRAVIS_TAG;
    openssl aes-256-cbc -K $encrypted_39b9ec781f4f_key -iv $encrypted_39b9ec781f4f_iv -in scripts/key/id_rsa.enc -out ~/.ssh/id_rsa -d || exit 1;
    chmod 0600 ~/.ssh/id_rsa || exit 1;
    git clone git@github.com:VIPAAR/travis-helper-scripts.git travis-helper-scripts || exit 1;
    ./scripts/build-release $VER $HL_BASE_IMAGE;
    fi

